---
- hosts: localhost
  become: yes
  vars_files:
   - vault.yml
  vars:
    bucket: gitrepo-backup
    gitrepo: false  
    gitlatestfiles: true
  tasks:
  - name: Gathering all the repositories
    shell: |
      curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer {{token}}" https://api.github.com/orgs/safestart/repos
    args:
       warn: false
    register: git_repo_list       
    
  - name: Uploading all files from github repo to {{bucket}} s3 bucket
    shell: |
      git config --global credential.helper cache
      git clone https://{{ token }}@{{ item | regex_replace('https://', '') }} 
      aws s3 cp {{ item | regex_search('[^//]+$') | regex_replace('.git', '') }} s3://{{bucket}}/{{ item | regex_search('[^//]+$') | regex_replace('.git', '') }} --exclude ".git/*" --recursive
      rm -rf {{ item | regex_search('[^//]+$') | regex_replace('.git', '') }}      
    loop: "{{ (git_repo_list.stdout | from_json) | map(attribute='clone_url') | list }}"
    args:
      chdir: /tmp
    when: gitrepo
 
  - name: Uploading the latest updated or created files from github repo to {{bucket}} s3 bucket, since a day
    shell: |
      git config --global credential.helper cache
      git clone https://{{token}}@{{item}} && cd {{ item | regex_search('[^//]+$') | regex_replace('.git', '') }}
      if [ $(git log --pretty=format: --name-only --since="1 days ago" --until="1 seconds ago" | sort | uniq | awk 'NF' | wc -l) -gt 0 ]; then 
        for filepush in `git log --pretty=format: --name-only --since="1 days ago" --until="1 seconds ago" | sort | uniq | awk 'NF'`; do
           aws s3 cp $filepush s3://{{bucket}}/$filepush
        done
      fi
    loop: "{{ (git_repo_list.stdout | from_json) | map(attribute='clone_url') | list }}"
    args:
      chdir: /tmp    
    when: gitlatestfiles

#  - name: Listing out the repositories
#    debug: msg="{{ (git_repo_list.stdout | from_json) | map(attribute='clone_url') | join(' , ')  }}"
#    register: git_repo_url
    
#  - name: Filtering out repo name
#    set_fact:
#      git_repo_name: "{{ item | regex_search('[^//]+$') | regex_replace('.git', '') }}"
#    loop: "{{ git_repo_url.split(',') }}"

#for filedelete in `git log --name-only --since="2 days ago" --until="1 seconds ago" | sort | uniq | awk 'NF' | grep "    Delete " | awk '{print $2}'`
#do
#         git log --pretty="The author of %h was %an, %ar%nCommit message: %s%n" > {{git_repo_name}}_commit_log.txt
#         aws s3 cp {{ item | regex_search('[^//]+$') | regex_replace('.git', '') }}_commit_log.txt s3://{{bucket}}/{{ item | regex_search('[^//]+$') | regex_replace('.git', '') }}/{{ item | regex_search('[^//]+$') | regex_replace('.git', '') }}_commit_log.txt
#    aws s3api delete-object --bucket {{bucket}} --key $filedelete
#done

